# Generated by Django 5.2.5 on 2025-09-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontPage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="frontpage",
            name="is_implemented",
            field=models.BooleanField(default=False),
        ),
    ]
