# Generated by Django 5.2.5 on 2025-09-21 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discussion", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="discussion",
            old_name="project",
            new_name="project_under",
        ),
    ]
