# Generated by Django 5.2.5 on 2025-09-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussion", "0002_rename_project_discussion_project_under"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discussionchat",
            name="is_by_user",
            field=models.BooleanField(default=True),
        ),
    ]
