# Generated by Django 5.2.5 on 2025-12-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0003_alter_discussionchat_is_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
    ]
