# Generated by Django 5.2.5 on 2026-02-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussion", "0004_discussion_is_occupied"),
    ]

    operations = [
        migrations.AddField(
            model_name="discussion",
            name="short_summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
