# Generated by Django 5.2.5 on 2025-10-03 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("frontFile", "0002_remove_frontfile_created_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FrontFile",
        ),
    ]
