# Generated by Django 5.2.5 on 2026-01-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontFile", "0003_delete_frontfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectfile",
            name="draft_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
