# Generated by Django 5.2.5 on 2025-12-19 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontFile', '0003_delete_frontfile'),
        ('project', '0004_alter_project_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_content', models.TextField(blank=True, null=True)),
                ('draft_type', models.CharField(choices=[('CREATE', '새 파일 생성'), ('UPDATE', '수정'), ('DELETE', '삭제')], default='UPDATE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontFile.folder')),
                ('project_under', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('target_file', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='frontFile.projectfile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('target_file__isnull', True)), fields=('project_under', 'folder', 'file_name'), name='unique_draft_creation_per_location')],
            },
        ),
    ]
