# Generated by Django 5.2.5 on 2026-02-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontFile", "0004_projectfile_draft_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
