# Generated by Django 5.2.5 on 2026-02-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontFile", "0005_folder_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectfile",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="projectfile",
            name="draft_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="projectfile",
            name="is_required",
            field=models.BooleanField(default=False),
        ),
    ]
