# Generated by Django 5.2.5 on 2026-02-25 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("frontFile", "0006_projectfile_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectfile",
            options={"ordering": ["project_under"]},
        ),
    ]
