# Generated by Django 5.2.5 on 2025-08-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apidoc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apidoc",
            name="query_params",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="apidoc",
            name="request_headers",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
