# Generated by Django 5.2.5 on 2026-02-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apidoc", "0003_apidoc_created_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apidoc",
            options={"ordering": ["method_order", "url"]},
        ),
        migrations.AddField(
            model_name="apidoc",
            name="method_order",
            field=models.IntegerField(db_index=True, default=0, editable=False),
        ),
    ]
