# Generated by Django 5.2.5 on 2026-02-13 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apidoc", "0004_apirequestbody_apiresponsebody"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apiresponsebody",
            options={"ordering": ["http_status"]},
        ),
        migrations.RemoveField(
            model_name="apidoc",
            name="request_format",
        ),
        migrations.RemoveField(
            model_name="apidoc",
            name="response_format",
        ),
        migrations.AlterField(
            model_name="apirequestbody",
            name="apidoc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="request_bodies",
                to="apidoc.apidoc",
            ),
        ),
        migrations.AlterField(
            model_name="apiresponsebody",
            name="apidoc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="response_bodies",
                to="apidoc.apidoc",
            ),
        ),
        migrations.AlterField(
            model_name="apiresponsebody",
            name="http_status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (100, "100 Continue"),
                    (101, "101 Switching Protocols"),
                    (200, "200 OK"),
                    (201, "201 Created"),
                    (202, "202 Accepted"),
                    (204, "204 No Content"),
                    (205, "205 Reset Content"),
                    (206, "206 Partial Content"),
                    (300, "300 Multiple Choices"),
                    (301, "301 Moved Permanently"),
                    (302, "302 Found"),
                    (304, "304 Not Modified"),
                    (307, "307 Temporary Redirect"),
                    (308, "308 Permanent Redirect"),
                    (400, "400 Bad Request"),
                    (401, "401 Unauthorized"),
                    (403, "403 Forbidden"),
                    (404, "404 Not Found"),
                    (405, "405 Method Not Allowed"),
                    (406, "406 Not Acceptable"),
                    (408, "408 Request Timeout"),
                    (409, "409 Conflict"),
                    (410, "410 Gone"),
                    (415, "415 Unsupported Media Type"),
                    (422, "422 Unprocessable Entity"),
                    (429, "429 Too Many Requests"),
                    (500, "500 Internal Server Error"),
                    (501, "501 Not Implemented"),
                    (502, "502 Bad Gateway"),
                    (503, "503 Service Unavailable"),
                    (504, "504 Gateway Timeout"),
                ],
                default=200,
            ),
        ),
        migrations.AlterField(
            model_name="apiresponsebody",
            name="response_example",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
