# Generated by Django 5.2.5 on 2026-02-10 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apidoc", "0005_auto_20260210_1921"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apidoc",
            options={"ordering": ["url", "method_order"]},
        ),
    ]
