# Generated by Django 5.2.5 on 2026-02-14 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apidoc", "0005_alter_apiresponsebody_options_and_more"),
        ("apidoc", "0006_alter_apidoc_options"),
    ]

    operations = []
