# Generated by Django 5.2.5 on 2026-02-16 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apidoc", "0007_merge_20260214_1426"),
        ("project", "0007_alter_project_to_do_request"),
    ]

    operations = [
        migrations.CreateModel(
            name="URLParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parameter", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "project_under",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="apidoc",
            name="url_parameters",
            field=models.ManyToManyField(
                related_name="apidocs", to="apidoc.urlparameter"
            ),
        ),
    ]
