# Generated by Django 5.2.5 on 2026-02-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apidoc", "0008_urlparameter_apidoc_url_parameters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apidoc",
            name="url_parameters",
            field=models.ManyToManyField(
                blank=True, related_name="apidocs", to="apidoc.urlparameter"
            ),
        ),
    ]
