# Generated by Django 5.2.5 on 2025-08-17 09:39

import django.utils.timezone
import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aruser",
            name="gemini_key_encrypted",
            field=encrypted_model_fields.fields.EncryptedCharField(
                default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
