# Generated by Django 5.2.5 on 2025-12-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='base_url',
            field=models.URLField(default='http://test.com'),
            preserve_default=False,
        ),
    ]
