# Generated by Django 5.2.5 on 2026-01-05 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_project_base_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="base_url",
        ),
        migrations.AddField(
            model_name="project",
            name="base_api_url",
            field=models.URLField(default="https://example.com"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="base_web_url",
            field=models.URLField(default="https://test.com"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
