# Generated by Django 5.2.5 on 2025-12-19 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_base_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='base_url',
            new_name='base_web_url',
        ),
        migrations.AddField(
            model_name='project',
            name='base_api_url',
            field=models.URLField(default='https://ar-web.delightfulisland-8239f9f6.koreacentral.azurecontainerapps.io'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
