# Generated by Django 5.2.5 on 2026-01-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_remove_project_base_url_project_base_api_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="handover_context",
            field=models.TextField(default="No Handover Context Yet"),
        ),
    ]
