# Generated by Django 5.2.5 on 2026-01-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_project_handover_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="to_do_request",
            field=models.TextField(
                blank=True,
                default="package.json, src/App.jsx, src/App.css 파일 내용을 반드시 추가하세요.",
                null=True,
            ),
        ),
    ]
