# Generated by Django 5.2.5 on 2026-02-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_project_to_do_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="handover_draft",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="instruction",
            field=models.TextField(blank=True, null=True),
        ),
    ]
