# Generated by Django 5.2.5 on 2026-02-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_project_handover_draft_project_instruction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="to_do_request",
            field=models.TextField(
                blank=True,
                default="package.json, src/App.jsx, src/App.css, src/index.css 파일 내용을 반드시 추가하세요.",
                null=True,
            ),
        ),
    ]
