# Generated by Django 5.2.5 on 2026-01-06 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("apidoc", "0003_apidoc_created_by"),
        ("discussion", "0004_discussion_is_occupied"),
        ("frontFile", "0004_projectfile_draft_content"),
        ("frontPage", "0002_frontpage_is_implemented"),
        ("project", "0003_remove_project_base_url_project_base_api_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenerationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "진행 중"),
                            ("COMPLETED", "반영 완료"),
                            ("DISCARDED", "폐기됨"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
                (
                    "related_apidocs",
                    models.ManyToManyField(related_name="sessions", to="apidoc.apidoc"),
                ),
                (
                    "related_discussions",
                    models.ManyToManyField(
                        related_name="sessions", to="discussion.discussion"
                    ),
                ),
                (
                    "related_files",
                    models.ManyToManyField(
                        related_name="sessions", to="frontFile.projectfile"
                    ),
                ),
                (
                    "related_folders",
                    models.ManyToManyField(
                        related_name="sessions", to="frontFile.folder"
                    ),
                ),
                (
                    "related_pages",
                    models.ManyToManyField(
                        related_name="sessions", to="frontPage.frontpage"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_by_user", models.BooleanField(default=True)),
                (
                    "session_under",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="codeGenerate.generationsession",
                    ),
                ),
            ],
        ),
    ]
