# Generated by Django 5.2.5 on 2026-01-06 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("codeGenerate", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="generationsession",
            old_name="project",
            new_name="project_under",
        ),
    ]
