# Generated by Django 5.2.5 on 2026-01-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apidoc", "0003_apidoc_created_by"),
        ("codeGenerate", "0002_rename_project_generationsession_project_under"),
        ("discussion", "0004_discussion_is_occupied"),
        ("frontFile", "0004_projectfile_draft_content"),
        ("frontPage", "0002_frontpage_is_implemented"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generationsession",
            name="related_apidocs",
            field=models.ManyToManyField(
                blank=True, related_name="sessions", to="apidoc.apidoc"
            ),
        ),
        migrations.AlterField(
            model_name="generationsession",
            name="related_discussions",
            field=models.ManyToManyField(
                blank=True, related_name="sessions", to="discussion.discussion"
            ),
        ),
        migrations.AlterField(
            model_name="generationsession",
            name="related_files",
            field=models.ManyToManyField(
                blank=True, related_name="sessions", to="frontFile.projectfile"
            ),
        ),
        migrations.AlterField(
            model_name="generationsession",
            name="related_folders",
            field=models.ManyToManyField(
                blank=True, related_name="sessions", to="frontFile.folder"
            ),
        ),
        migrations.AlterField(
            model_name="generationsession",
            name="related_pages",
            field=models.ManyToManyField(
                blank=True, related_name="sessions", to="frontPage.frontpage"
            ),
        ),
    ]
