# Generated by Django 5.2.5 on 2026-01-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeGenerate', '0003_alter_generationsession_related_apidocs_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionchat',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='generationsession',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
    ]
